treemap
    Operations
        Salaries: 700
        Equipment: 200
        Supplies: 100
    Marketing
        Advertising: 400
        Events: 100
    R&D
        Research: 300
        Prototyping: 150
        Testing: 50
