quadrantChart
  title Analytics Platforms
  x-axis Completeness of Vision -->
  y-axis Ability to Execute -->
  quadrant-1 Leaders
  quadrant-2 Challengers
  quadrant-3 Niche Players
  quadrant-4 Visionaries
  Microsoft: [0.78, 0.80]
  Salesforce: [0.60, 0.65]
  SAP: [0.55, 0.50]
  Oracle: [0.50, 0.55]
  IBM: [0.45, 0.42]
  Qlik: [0.58, 0.48]
  Tableau: [0.72, 0.70]
  SAS: [0.40, 0.60]
