timeline
    title Space Exploration
    1957 : Sputnik : Laika
    1961 : Gagarin : Shepard
    1969 : Apollo 11 : Moon landing : Armstrong walks
    1981 : Space Shuttle : Columbia launch
    1998 : ISS construction begins
    2020 : SpaceX Crew Dragon : Mars Perseverance
