flowchart TD
    Root[Router] --> C1[Shard 1]
    Root --> C2[Shard 2]
    Root --> C3[Shard 3]
    Root --> C4[Shard 4]
    Root --> C5[Shard 5]
    Root --> C6[Shard 6]
    Root --> C7[Shard 7]
    Root --> C8[Shard 8]
    Root --> C9[Shard 9]
    Root --> C10[Shard 10]
    C1 --> C1A[Replica 1A]
    C1 --> C1B[Replica 1B]
    C2 --> C2A[Replica 2A]
    C2 --> C2B[Replica 2B]
    C3 --> C3A[Replica 3A]
    C3 --> C3B[Replica 3B]
    C4 --> C4A[Replica 4A]
    C4 --> C4B[Replica 4B]
    C5 --> C5A[Replica 5A]
    C5 --> C5B[Replica 5B]
    C6 --> C6A[Replica 6A]
    C6 --> C6B[Replica 6B]
    C7 --> C7A[Replica 7A]
    C7 --> C7B[Replica 7B]
    C8 --> C8A[Replica 8A]
    C8 --> C8B[Replica 8B]
    C9 --> C9A[Replica 9A]
    C9 --> C9B[Replica 9B]
    C10 --> C10A[Replica 10A]
    C10 --> C10B[Replica 10B]
