packet-beta
title "IPv4 Header"
0-3: "Version"
4-7: "IHL"
8-15: "DSCP/ECN"
16-31: "Total Length"
32-47: "Identification"
48-50: "Flags"
51-63: "Fragment Offset"
64-71: "TTL"
72-79: "Protocol"
80-95: "Header Checksum"
96-127: "Source Address"
128-159: "Destination Address"
