packet-beta
+4: "Ver"
+4: "IHL"
+8: "DSCP"
+16: "Total Length"
+16: "Identification"
+3: "Flags"
+13: "Fragment Offset"
+8: "TTL"
+8: "Protocol"
+16: "Checksum"
+32: "Source Address"
+32: "Destination Address"
