kanban
    Backlog
        id1[Design homepage]
        id2[Write API docs]
        id3[Research competitors]
    In Progress
        id4[Build login page]
        id5[Set up CI/CD]
    Review
        id6[Code review PR #42]
    Done
        id7[Deploy staging]
        id8[Database migration]
