use gpui::*;
use rusty_mermaid_core::Theme;
use rusty_mermaid_viewport::ViewportState;

// Generated by build.rs from tests/golden/mmd/**/*.mmd
include!(concat!(env!("OUT_DIR"), "/diagrams.rs"));

const FONT_FAMILY: &str = rusty_mermaid_core::font_fallback::PRIMARY_FONT;

struct GalleryApp {
    current: usize,
    cached_idx: usize,
    cached_scene: Option<rusty_mermaid_core::Scene>,
}

impl GalleryApp {
    fn ensure_scene(&mut self) {
        if self.cached_scene.is_none() || self.cached_idx != self.current {
            let (name, mmd) = DIAGRAMS[self.current];
            eprintln!("Loading diagram {}: {name}", self.current);
            self.cached_scene = match rusty_mermaid_diagrams::render_to_scene(mmd) {
                Ok(s) => Some(s),
                Err(e) => {
                    eprintln!("  FAILED: {e}");
                    None
                }
            };
            self.cached_idx = self.current;
        }
    }
}

impl Render for GalleryApp {
    fn render(&mut self, _window: &mut Window, cx: &mut Context<Self>) -> impl IntoElement {
        self.ensure_scene();

        let (name, _) = DIAGRAMS[self.current];
        let total = DIAGRAMS.len();
        let idx = self.current;
        let theme = Theme::light();
        let padding = theme.padding;

        let (scene_w, scene_h) = match &self.cached_scene {
            Some(s) => (s.width + padding * 2.0, s.height + padding * 2.0),
            None => (400.0, 200.0),
        };

        div()
            .flex()
            .flex_col()
            .size_full()
            .bg(rgb(0xf5f5f5))
            .font_family(FONT_FAMILY)
            // Header — fixed height
            .child(
                div()
                    .flex()
                    .items_center()
                    .justify_between()
                    .px_4()
                    .py_2()
                    .bg(rgb(0xffffff))
                    .border_b_1()
                    .border_color(rgb(0xeeeeee))
                    .flex_shrink_0()
                    .child(
                        div().flex().items_center().gap_3()
                            .child(
                                div().id("prev").px_3().py_1()
                                    .bg(rgb(0xf0f0f0)).rounded_md().cursor_pointer()
                                    .child("◀ Prev")
                                    .on_click(cx.listener(|this, _, _, _| {
                                        this.current = if this.current > 0 {
                                            this.current - 1
                                        } else {
                                            DIAGRAMS.len() - 1
                                        };
                                    }))
                            )
                            .child(
                                div().text_sm().text_color(rgb(0x555555))
                                    .child(format!("{} / {}  —  {}", idx + 1, total, name))
                            )
                            .child(
                                div().id("next").px_3().py_1()
                                    .bg(rgb(0xf0f0f0)).rounded_md().cursor_pointer()
                                    .child("Next ▶")
                                    .on_click(cx.listener(|this, _, _, _| {
                                        this.current = (this.current + 1) % DIAGRAMS.len();
                                    }))
                            )
                    )
                    .child(
                        div().text_sm().text_color(rgb(0x9370db))
                            .child("rusty-mermaid gpui gallery")
                    )
            )
            // Diagram area — scrollable, takes remaining space
            .child(
                div().id("scroll-area").flex_1().p_4().overflow_scroll()
                    .child(
                        div()
                            .bg(rgb(0xffffff))
                            .rounded_lg()
                            .p_4()
                            .shadow_sm()
                            // Explicit size from scene dimensions
                            .w(px(scene_w as f32 + 32.0)) // + padding
                            .h(px(scene_h as f32 + 32.0))
                            .child({
                                // Take scene temporarily — canvas callback moves it
                                let scene = self.cached_scene.take();
                                if let Some(s) = scene {
                                    let s_clone = s.clone(); // keep for cache
                                    self.cached_scene = Some(s_clone);
                                    div().child(
                                        rusty_mermaid_gpui::render_element(
                                            s,
                                            theme,
                                            ViewportState::default(),
                                        )
                                    )
                                } else {
                                    div().child("Failed to parse diagram")
                                }
                            })
                    )
            )
    }
}

fn main() {
    Application::new().run(|cx: &mut App| {
        let bounds = Bounds::centered(None, size(px(1200.0), px(800.0)), cx);
        cx.open_window(
            WindowOptions {
                window_bounds: Some(WindowBounds::Windowed(bounds)),
                titlebar: Some(TitlebarOptions {
                    title: Some("rusty-mermaid gpui gallery".into()),
                    ..Default::default()
                }),
                ..Default::default()
            },
            |_, cx| cx.new(|_| GalleryApp { current: 0, cached_idx: usize::MAX, cached_scene: None }),
        )
        .unwrap();
    });
}
