gitGraph
    commit id: "normal"
    commit id: "rev" type: REVERSE
    commit id: "hl" type: HIGHLIGHT
    branch hotfix
    commit id: "fix-1"
    checkout main
    merge hotfix tag: "v1.1"
    commit
