use std::cell::RefCell;
use std::rc::Rc;

use wasm_bindgen::prelude::*;
use wasm_bindgen_futures::JsFuture;
use web_sys::HtmlCanvasElement;

use rusty_mermaid_core::font_fallback::FontSlot;
use rusty_mermaid_core::{Point, Theme};
use rusty_mermaid_viewport::{ViewportAction, ViewportState, apply};
use rusty_mermaid_wgpu::{build_vello_scene, set_external_font};

// Generated by build.rs from tests/golden/mmd/**/*.mmd
include!(concat!(env!("OUT_DIR"), "/diagrams.rs"));

/// Blit shader: copies Rgba8Unorm texture to surface format.
const BLIT_SHADER: &str = r"
@group(0) @binding(0) var src_tex: texture_2d<f32>;
@group(0) @binding(1) var src_sampler: sampler;

struct VertexOutput {
    @builtin(position) pos: vec4<f32>,
    @location(0) uv: vec2<f32>,
};

@vertex
fn vs_main(@builtin(vertex_index) idx: u32) -> VertexOutput {
    var positions = array<vec2<f32>, 3>(
        vec2(-1.0, -1.0),
        vec2( 3.0, -1.0),
        vec2(-1.0,  3.0),
    );
    var uvs = array<vec2<f32>, 3>(
        vec2(0.0, 1.0),
        vec2(2.0, 1.0),
        vec2(0.0, -1.0),
    );
    var out: VertexOutput;
    out.pos = vec4(positions[idx], 0.0, 1.0);
    out.uv = uvs[idx];
    return out;
}

@fragment
fn fs_main(in: VertexOutput) -> @location(0) vec4<f32> {
    return textureSample(src_tex, src_sampler, in.uv);
}
";

struct GpuState {
    device: wgpu::Device,
    queue: wgpu::Queue,
    renderer: vello::Renderer,
    blit_pipeline: wgpu::RenderPipeline,
    blit_bind_group_layout: wgpu::BindGroupLayout,
    sampler: wgpu::Sampler,
    surface_format: wgpu::TextureFormat,
    is_dark: bool,
}

/// Shared interactive state for single-diagram view.
struct AppState {
    gpu: GpuState,
    viewport: ViewportState,
    current_idx: usize,
    /// Mouse drag state: last position during drag.
    drag_origin: Option<(f64, f64)>,
}

#[wasm_bindgen(start)]
pub async fn main() -> Result<(), JsValue> {
    console_error_panic_hook::set_once();

    let window = web_sys::window().unwrap();
    let document = window.document().unwrap();

    // Populate diagram selector
    let select = document
        .get_element_by_id("diagram-select")
        .unwrap()
        .dyn_into::<web_sys::HtmlSelectElement>()
        .unwrap();

    for (name, _) in DIAGRAMS {
        let option = document.create_element("option").unwrap();
        option.set_text_content(Some(name));
        option.set_attribute("value", name).unwrap();
        select.append_child(&option).unwrap();
    }

    let canvas = document
        .get_element_by_id("diagram-canvas")
        .unwrap()
        .dyn_into::<HtmlCanvasElement>()
        .unwrap();

    // Init WebGPU
    let instance = wgpu::Instance::new(&wgpu::InstanceDescriptor {
        backends: wgpu::Backends::BROWSER_WEBGPU,
        ..Default::default()
    });

    let surface = instance
        .create_surface(wgpu::SurfaceTarget::Canvas(canvas.clone()))
        .unwrap();

    let adapter = instance
        .request_adapter(&wgpu::RequestAdapterOptions {
            compatible_surface: Some(&surface),
            power_preference: wgpu::PowerPreference::HighPerformance,
            ..Default::default()
        })
        .await
        .map_err(|e| JsValue::from_str(&format!("No WebGPU adapter: {e}")))?;

    let result: Result<(wgpu::Device, wgpu::Queue), wgpu::RequestDeviceError> = adapter
        .request_device(&wgpu::DeviceDescriptor::default())
        .await;
    let (device, queue) =
        result.map_err(|e| JsValue::from_str(&format!("Device creation failed: {e}")))?;

    let renderer = vello::Renderer::new(
        &device,
        vello::RendererOptions {
            use_cpu: false,
            antialiasing_support: vello::AaSupport::all(),
            num_init_threads: None,
            pipeline_cache: None,
        },
    )
    .map_err(|e| JsValue::from_str(&format!("Vello renderer failed: {e}")))?;

    let caps = surface.get_capabilities(&adapter);
    let surface_format = caps
        .formats
        .first()
        .copied()
        .unwrap_or(wgpu::TextureFormat::Bgra8Unorm);

    // Build blit pipeline
    let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
        label: Some("blit_shader"),
        source: wgpu::ShaderSource::Wgsl(BLIT_SHADER.into()),
    });

    let blit_bind_group_layout =
        device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: Some("blit_bgl"),
            entries: &[
                wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::FRAGMENT,
                    ty: wgpu::BindingType::Texture {
                        sample_type: wgpu::TextureSampleType::Float { filterable: true },
                        view_dimension: wgpu::TextureViewDimension::D2,
                        multisampled: false,
                    },
                    count: None,
                },
                wgpu::BindGroupLayoutEntry {
                    binding: 1,
                    visibility: wgpu::ShaderStages::FRAGMENT,
                    ty: wgpu::BindingType::Sampler(wgpu::SamplerBindingType::Filtering),
                    count: None,
                },
            ],
        });

    let pipeline_layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
        label: Some("blit_layout"),
        bind_group_layouts: &[&blit_bind_group_layout],
        immediate_size: 0,
    });

    let blit_pipeline = device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
        label: Some("blit_pipeline"),
        layout: Some(&pipeline_layout),
        vertex: wgpu::VertexState {
            module: &shader,
            entry_point: Some("vs_main"),
            buffers: &[],
            compilation_options: Default::default(),
        },
        fragment: Some(wgpu::FragmentState {
            module: &shader,
            entry_point: Some("fs_main"),
            targets: &[Some(wgpu::ColorTargetState {
                format: surface_format,
                blend: None,
                write_mask: wgpu::ColorWrites::ALL,
            })],
            compilation_options: Default::default(),
        }),
        primitive: wgpu::PrimitiveState::default(),
        depth_stencil: None,
        multisample: wgpu::MultisampleState::default(),
        multiview_mask: None,
        cache: None,
    });

    let sampler = device.create_sampler(&wgpu::SamplerDescriptor {
        mag_filter: wgpu::FilterMode::Linear,
        min_filter: wgpu::FilterMode::Linear,
        ..Default::default()
    });

    let gpu = GpuState {
        device,
        queue,
        renderer,
        blit_pipeline,
        blit_bind_group_layout,
        sampler,
        surface_format,
        is_dark: false,
    };

    fetch_needed_fonts().await;

    let app = Rc::new(RefCell::new(AppState {
        gpu,
        viewport: ViewportState::default(),
        current_idx: 0,
        drag_origin: None,
    }));
    let surface = Rc::new(surface);

    // Render first diagram
    render_current(&canvas, &surface, &mut app.borrow_mut());

    // Render gallery view
    render_gallery(&canvas, &surface, &mut app.borrow_mut().gpu);

    // Diagram select handler
    {
        let canvas_s = canvas.clone();
        let app_s = app.clone();
        let surface_s = surface.clone();
        let select_closure = Closure::wrap(Box::new(move || {
            let document = web_sys::window().unwrap().document().unwrap();
            let sel = document
                .get_element_by_id("diagram-select")
                .unwrap()
                .dyn_into::<web_sys::HtmlSelectElement>()
                .unwrap();
            let mut state = app_s.borrow_mut();
            state.current_idx = sel.selected_index() as usize;
            state.viewport = ViewportState::default();
            render_current(&canvas_s, &surface_s, &mut state);
        }) as Box<dyn FnMut()>);
        select.set_onchange(Some(select_closure.as_ref().unchecked_ref()));
        select_closure.forget();
    }

    // ── Mouse wheel → zoom ──
    {
        let canvas_s = canvas.clone();
        let app_s = app.clone();
        let surface_s = surface.clone();
        let wheel_closure = Closure::wrap(Box::new(move |event: web_sys::WheelEvent| {
            event.prevent_default();
            let factor = if event.delta_y() < 0.0 {
                1.1
            } else {
                1.0 / 1.1
            };
            let center = Point::new(event.offset_x() as f64, event.offset_y() as f64);
            let mut state = app_s.borrow_mut();
            state.viewport = apply(&state.viewport, &ViewportAction::Zoom { factor, center });
            render_current(&canvas_s, &surface_s, &mut state);
        }) as Box<dyn FnMut(_)>);
        canvas
            .add_event_listener_with_callback("wheel", wheel_closure.as_ref().unchecked_ref())
            .unwrap();
        wheel_closure.forget();
    }

    // ── Mouse drag → pan ──
    {
        let app_s = app.clone();
        let mousedown = Closure::wrap(Box::new(move |event: web_sys::MouseEvent| {
            let mut state = app_s.borrow_mut();
            state.drag_origin = Some((event.client_x() as f64, event.client_y() as f64));
        }) as Box<dyn FnMut(_)>);
        canvas
            .add_event_listener_with_callback("mousedown", mousedown.as_ref().unchecked_ref())
            .unwrap();
        mousedown.forget();
    }
    {
        let canvas_s = canvas.clone();
        let app_s = app.clone();
        let surface_s = surface.clone();
        let mousemove = Closure::wrap(Box::new(move |event: web_sys::MouseEvent| {
            let mut state = app_s.borrow_mut();
            if let Some((ox, oy)) = state.drag_origin {
                let dx = event.client_x() as f64 - ox;
                let dy = event.client_y() as f64 - oy;
                state.drag_origin = Some((event.client_x() as f64, event.client_y() as f64));
                state.viewport = apply(&state.viewport, &ViewportAction::Pan { dx, dy });
                render_current(&canvas_s, &surface_s, &mut state);
            }
        }) as Box<dyn FnMut(_)>);
        canvas
            .add_event_listener_with_callback("mousemove", mousemove.as_ref().unchecked_ref())
            .unwrap();
        mousemove.forget();
    }
    {
        let app_s = app.clone();
        let mouseup = Closure::wrap(Box::new(move |_event: web_sys::MouseEvent| {
            app_s.borrow_mut().drag_origin = None;
        }) as Box<dyn FnMut(_)>);
        canvas
            .add_event_listener_with_callback("mouseup", mouseup.as_ref().unchecked_ref())
            .unwrap();
        canvas
            .add_event_listener_with_callback("mouseleave", mouseup.as_ref().unchecked_ref())
            .unwrap();
        mouseup.forget();
    }

    // ── Double-click → reset viewport ──
    {
        let canvas_s = canvas.clone();
        let app_s = app.clone();
        let surface_s = surface.clone();
        let dblclick = Closure::wrap(Box::new(move |_event: web_sys::MouseEvent| {
            let mut state = app_s.borrow_mut();
            state.viewport = ViewportState::default();
            render_current(&canvas_s, &surface_s, &mut state);
        }) as Box<dyn FnMut(_)>);
        canvas
            .add_event_listener_with_callback("dblclick", dblclick.as_ref().unchecked_ref())
            .unwrap();
        dblclick.forget();
    }

    if let Some(el) = document.get_element_by_id("loading") {
        let _ = el.set_attribute("style", "display:none");
    }
    if let Some(el) = document.get_element_by_id("diagram-count") {
        el.set_text_content(Some(&format!("{}", DIAGRAMS.len())));
    }

    // Show gallery by default
    if let Some(el) = document.get_element_by_id("gallery-view") {
        let _ = el.set_attribute("style", "display:block");
    }

    Ok(())
}

fn render_gallery(
    canvas: &HtmlCanvasElement,
    surface: &wgpu::Surface<'static>,
    gpu: &mut GpuState,
) {
    let document = web_sys::window().unwrap().document().unwrap();
    let gallery_div = document.get_element_by_id("gallery-view").unwrap();
    gallery_div.set_inner_html("");

    // Group diagrams by section (prefix before /)
    let mut current_section = String::new();

    for (i, (name, _)) in DIAGRAMS.iter().enumerate() {
        let section = name.split('/').next().unwrap_or(name);

        if section != current_section {
            current_section = section.to_string();
            let h = document.create_element("h2").unwrap();
            h.set_class_name("section-title");
            h.set_text_content(Some(section));
            gallery_div.append_child(&h).unwrap();
        }

        // Render diagram to canvas (static, no viewport)
        render_static(canvas, surface, gpu, i);

        // Get CSS dimensions (before DPR scaling)
        let Ok(scene) = rusty_mermaid_diagrams::render_to_scene(DIAGRAMS[i].1) else {
            continue;
        };
        let is_dark = web_sys::window()
            .and_then(|w| w.document())
            .and_then(|d| d.document_element())
            .map(|el| el.class_list().contains("dark"))
            .unwrap_or(false);
        let theme = if is_dark {
            Theme::dark()
        } else {
            Theme::light()
        };
        let css_w = scene.width + theme.padding * 2.0;
        let css_h = scene.height + theme.padding * 2.0;

        // Capture as data URL
        let data_url = canvas.to_data_url().unwrap_or_default();

        let card = document.create_element("div").unwrap();
        card.set_class_name("card");

        let title = document.create_element("h2").unwrap();
        title.set_text_content(Some(name));
        card.append_child(&title).unwrap();

        let img = document.create_element("img").unwrap();
        img.set_attribute("src", &data_url).unwrap();
        img.set_attribute("alt", name).unwrap();
        // Set only width — height auto-scales to preserve aspect ratio
        // when max-width:100% constrains wide diagrams
        let _ = img.set_attribute("style", &format!("width:{}px;height:auto", css_w as u32));
        card.append_child(&img).unwrap();

        gallery_div.append_child(&card).unwrap();
    }
}

/// Render a diagram at 1:1 scale (no pan/zoom) — used by gallery view.
fn render_static(
    canvas: &HtmlCanvasElement,
    surface: &wgpu::Surface<'static>,
    gpu: &mut GpuState,
    idx: usize,
) {
    if idx >= DIAGRAMS.len() {
        return;
    }
    let (_, mmd) = DIAGRAMS[idx];
    let Ok(scene) = rusty_mermaid_diagrams::render_to_scene(mmd, &Theme::default()) else {
        return;
    };

    let is_dark = web_sys::window()
        .and_then(|w| w.document())
        .and_then(|d| d.document_element())
        .map(|el| el.class_list().contains("dark"))
        .unwrap_or(false);
    gpu.is_dark = is_dark;
    let theme = if is_dark {
        Theme::dark()
    } else {
        Theme::light()
    };
    let dpr = web_sys::window().unwrap().device_pixel_ratio();
    let w = scene.width + theme.padding * 2.0;
    let h = scene.height + theme.padding * 2.0;
    let pixel_w = (w * dpr) as u32;
    let pixel_h = (h * dpr) as u32;

    canvas.set_width(pixel_w);
    canvas.set_height(pixel_h);
    let style = canvas.style();
    let _ = style.set_property("width", &format!("{w}px"));
    let _ = style.set_property("height", &format!("{h}px"));

    let viewport = ViewportState {
        zoom: dpr,
        ..Default::default()
    };
    let vello_scene = build_vello_scene(&scene, &theme, &viewport);
    render_vello(gpu, surface, &vello_scene, pixel_w, pixel_h);
}

fn render_current(
    canvas: &HtmlCanvasElement,
    surface: &wgpu::Surface<'static>,
    app: &mut AppState,
) {
    if app.current_idx >= DIAGRAMS.len() {
        return;
    }
    let (name, mmd) = DIAGRAMS[app.current_idx];

    // Update displayed name
    if let Some(el) = web_sys::window()
        .and_then(|w| w.document())
        .and_then(|d| d.get_element_by_id("diagram-name"))
    {
        el.set_text_content(Some(name));
    }

    let Ok(scene) = rusty_mermaid_diagrams::render_to_scene(mmd, &Theme::default()) else {
        web_sys::console::error_1(
            &format!("Failed to parse: {}", DIAGRAMS[app.current_idx].0).into(),
        );
        return;
    };

    // Read theme from DOM
    let is_dark = web_sys::window()
        .and_then(|w| w.document())
        .and_then(|d| d.document_element())
        .map(|el| el.class_list().contains("dark"))
        .unwrap_or(false);
    app.gpu.is_dark = is_dark;
    let theme = if is_dark {
        Theme::dark()
    } else {
        Theme::light()
    };
    let dpr = web_sys::window().unwrap().device_pixel_ratio();
    let padding = theme.padding;
    let w = scene.width + padding * 2.0;
    let h = scene.height + padding * 2.0;

    // Canvas size adapts to viewport zoom
    let total_zoom = app.viewport.zoom.max(0.1);
    let css_w = w * total_zoom;
    let css_h = h * total_zoom;
    let pixel_w = (css_w * dpr) as u32;
    let pixel_h = (css_h * dpr) as u32;

    canvas.set_width(pixel_w);
    canvas.set_height(pixel_h);
    let style = canvas.style();
    let _ = style.set_property("width", &format!("{css_w}px"));
    let _ = style.set_property("height", &format!("{css_h}px"));

    // Combine user viewport with DPR scaling
    let render_viewport = ViewportState {
        offset: Point::new(app.viewport.offset.x * dpr, app.viewport.offset.y * dpr),
        zoom: total_zoom * dpr,
        ..Default::default()
    };
    let vello_scene = build_vello_scene(&scene, &theme, &render_viewport);
    render_vello(&mut app.gpu, surface, &vello_scene, pixel_w, pixel_h);
}

/// Run the vello → blit GPU pipeline.
fn render_vello(
    gpu: &mut GpuState,
    surface: &wgpu::Surface<'static>,
    vello_scene: &vello::Scene,
    pixel_w: u32,
    pixel_h: u32,
) {
    surface.configure(
        &gpu.device,
        &wgpu::SurfaceConfiguration {
            usage: wgpu::TextureUsages::RENDER_ATTACHMENT,
            format: gpu.surface_format,
            width: pixel_w,
            height: pixel_h,
            present_mode: wgpu::PresentMode::AutoVsync,
            desired_maximum_frame_latency: 2,
            alpha_mode: wgpu::CompositeAlphaMode::Auto,
            view_formats: vec![],
        },
    );

    let vello_target = gpu.device.create_texture(&wgpu::TextureDescriptor {
        label: Some("vello_target"),
        size: wgpu::Extent3d {
            width: pixel_w,
            height: pixel_h,
            depth_or_array_layers: 1,
        },
        mip_level_count: 1,
        sample_count: 1,
        dimension: wgpu::TextureDimension::D2,
        format: wgpu::TextureFormat::Rgba8Unorm,
        usage: wgpu::TextureUsages::STORAGE_BINDING | wgpu::TextureUsages::TEXTURE_BINDING,
        view_formats: &[],
    });
    let vello_view = vello_target.create_view(&wgpu::TextureViewDescriptor::default());

    let bg = if gpu.is_dark {
        vello::peniko::Color::from_rgba8(30, 30, 46, 255)
    } else {
        vello::peniko::Color::from_rgba8(255, 255, 255, 255)
    };

    if let Err(e) = gpu.renderer.render_to_texture(
        &gpu.device,
        &gpu.queue,
        vello_scene,
        &vello_view,
        &vello::RenderParams {
            base_color: bg,
            width: pixel_w,
            height: pixel_h,
            antialiasing_method: vello::AaConfig::Msaa16,
        },
    ) {
        web_sys::console::error_1(&format!("Render failed: {e}").into());
        return;
    }

    let surface_texture = match surface.get_current_texture() {
        Ok(st) => st,
        Err(e) => {
            web_sys::console::error_1(&format!("Surface texture failed: {e}").into());
            return;
        }
    };
    let surface_view = surface_texture
        .texture
        .create_view(&wgpu::TextureViewDescriptor::default());

    let bind_group = gpu.device.create_bind_group(&wgpu::BindGroupDescriptor {
        label: Some("blit_bg"),
        layout: &gpu.blit_bind_group_layout,
        entries: &[
            wgpu::BindGroupEntry {
                binding: 0,
                resource: wgpu::BindingResource::TextureView(&vello_view),
            },
            wgpu::BindGroupEntry {
                binding: 1,
                resource: wgpu::BindingResource::Sampler(&gpu.sampler),
            },
        ],
    });

    let mut encoder = gpu.device.create_command_encoder(&Default::default());
    {
        let mut pass = encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
            label: Some("blit_pass"),
            color_attachments: &[Some(wgpu::RenderPassColorAttachment {
                view: &surface_view,
                depth_slice: None,
                resolve_target: None,
                ops: wgpu::Operations {
                    load: wgpu::LoadOp::Clear(wgpu::Color::WHITE),
                    store: wgpu::StoreOp::Store,
                },
            })],
            ..Default::default()
        });
        pass.set_pipeline(&gpu.blit_pipeline);
        pass.set_bind_group(0, &bind_group, &[]);
        pass.draw(0..3, 0..1);
    }
    gpu.queue.submit(Some(encoder.finish()));
    surface_texture.present();
}

/// Detect which external fonts are needed, fetch from CDN.
async fn fetch_needed_fonts() {
    use rusty_mermaid_core::font_fallback::{
        NOTO_COLOR_EMOJI_URL, NOTO_SANS_SC_URL, detect_external_fonts,
    };

    let mut all_text = String::new();
    for (_, mmd) in DIAGRAMS {
        all_text.push_str(mmd);
    }

    let (needs_cjk, needs_emoji) = detect_external_fonts(&all_text);
    if !needs_cjk && !needs_emoji {
        web_sys::console::log_1(&"No external fonts needed".into());
        return;
    }

    let window = web_sys::window().unwrap();

    if needs_cjk {
        web_sys::console::log_1(&"Fetching Noto Sans SC (CJK)...".into());
        match fetch_font_bytes(&window, NOTO_SANS_SC_URL).await {
            Ok(bytes) => {
                web_sys::console::log_1(&format!("  CJK: {} KB", bytes.len() / 1024).into());
                set_external_font(FontSlot::Cjk, bytes);
            }
            Err(e) => web_sys::console::warn_1(&format!("  CJK failed: {e:?}").into()),
        }
    }

    if needs_emoji {
        web_sys::console::log_1(&"Fetching Noto Color Emoji...".into());
        match fetch_font_bytes(&window, NOTO_COLOR_EMOJI_URL).await {
            Ok(bytes) => {
                web_sys::console::log_1(&format!("  Emoji: {} KB", bytes.len() / 1024).into());
                set_external_font(FontSlot::Emoji, bytes);
            }
            Err(e) => web_sys::console::warn_1(&format!("  Emoji failed: {e:?}").into()),
        }
    }
}

/// Fetch raw font bytes (TTF/OTF) from a direct URL.
async fn fetch_font_bytes(window: &web_sys::Window, url: &str) -> Result<Vec<u8>, JsValue> {
    let resp = JsFuture::from(window.fetch_with_str(url)).await?;
    let resp: web_sys::Response = resp.dyn_into()?;
    if !resp.ok() {
        return Err(JsValue::from_str(&format!("HTTP {}", resp.status())));
    }
    let buf = JsFuture::from(resp.array_buffer()?).await?;
    let uint8 = js_sys::Uint8Array::new(&buf);
    Ok(uint8.to_vec())
}
