mindmap
    Root
        Branch A
            A1
            A2
            A3
            A4
            A5
        Branch B
            B1
        Branch C
            C1
                C1a
                C1b
                C1c
            C2
