mindmap
    Programming
        Languages
            Rust
            Python
            JavaScript
        Paradigms
            Functional
            Object-Oriented
            Procedural
        Tools
            Git
            Docker
            CI/CD
