venn-beta
    title Data Engineering
    set A["SQL"]:35
    set B["Python"]:30
    set C["Spark"]:20
    union A,B["Pandas"]:12
    union B,C["PySpark"]:10
    union A,C["SparkSQL"]:8
    union A,B,C["All Skills"]:5
