sankey-beta
Coal,Electricity,46
Gas,Electricity,27
Nuclear,Electricity,18
Wind,Electricity,8
Solar,Electricity,4
Electricity,Residential,35
Electricity,Commercial,28
Electricity,Industrial,25
Electricity,Transport,15
