sankey-beta
"Heating & Cooling",Residential,50
"Heating & Cooling","Office Buildings",30
"Office Buildings","Energy Loss",8
Residential,"Energy Loss",12
Residential,"Useful Heat",38
"Office Buildings","Useful Heat",22
